###############################################################################
# SNMP daemon config for optiplex-two (LibreNMS)  snmpd.conf
###############################################################################

# Listen on all IPv4 addresses on UDP/161
agentAddress udp:161

# Read-only community "homelab" allowed from your LAN
# Change 192.168.200.0/24 if your subnet is different
rocommunity homelab 192.168.200.14

# Info displayed in LibreNMS
sysLocation Homelab
sysContact Thomas <[email protected]>
sysName optiplex-two
###############################################################################
